### ISSUE TITLE
it's solution*🤓 

### ISSUE THREAD

**Issue by AradiaIsStupid** [PHxii256/PHxii256#1]

**Comment by PHxii256** [comment]
![image](https://user-images.githubusercontent.com/69358352/209370179-706035c5-16b5-461b-9df5-4ea25fef1aee.png)

**Comment by AradiaIsStupid** [comment]
![image](https://user-images.githubusercontent.com/75750909/209376209-c100a5b9-a4b6-4be7-94a7-73871c5ba47c.png)
it's official* :neckbeard:

**Comment by AradiaIsStupid** [comment]
yes i will keep pointing out spelling mistakes until i am tired
